# Generated by Django 4.2.6 on 2024-11-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('released_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_avg', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
