# Generated by Django 4.2.16 on 2024-11-20 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_movies', through='movies.LikedMovie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_by',
            field=models.ManyToManyField(related_name='watched_movies', through='movies.WatchedMovie', to=settings.AUTH_USER_MODEL),
        ),
    ]
