# Generated by Django 4.2.6 on 2024-11-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedreview',
            old_name='liked_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='liked_by',
            new_name='liked_users',
        ),
        migrations.AlterField(
            model_name='likedreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='movies.review'),
        ),
    ]
